# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/OscopeWithZynq.xdc

# Block Designs: bd/OscopeWithZynq/OscopeWithZynq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OscopeWithZynq || ORIG_REF_NAME==OscopeWithZynq} -quiet] -quiet

# IP: bd/OscopeWithZynq/ip/OscopeWithZynq_enhancedPWM_0_0/OscopeWithZynq_enhancedPWM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OscopeWithZynq_enhancedPWM_0_0 || ORIG_REF_NAME==OscopeWithZynq_enhancedPWM_0_0} -quiet] -quiet

# IP: bd/OscopeWithZynq/ip/OscopeWithZynq_enhancedPWM_1_0/OscopeWithZynq_enhancedPWM_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OscopeWithZynq_enhancedPWM_1_0 || ORIG_REF_NAME==OscopeWithZynq_enhancedPWM_1_0} -quiet] -quiet

# IP: bd/OscopeWithZynq/ip/OscopeWithZynq_processing_system7_0_0/OscopeWithZynq_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OscopeWithZynq_processing_system7_0_0 || ORIG_REF_NAME==OscopeWithZynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/OscopeWithZynq/ip/OscopeWithZynq_xbar_0/OscopeWithZynq_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OscopeWithZynq_xbar_0 || ORIG_REF_NAME==OscopeWithZynq_xbar_0} -quiet] -quiet

# IP: bd/OscopeWithZynq/ip/OscopeWithZynq_ps7_0_axi_periph_0/OscopeWithZynq_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OscopeWithZynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==OscopeWithZynq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/OscopeWithZynq/ip/OscopeWithZynq_rst_ps7_0_50M_0/OscopeWithZynq_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OscopeWithZynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==OscopeWithZynq_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/OscopeWithZynq/ip/OscopeWithZynq_acquireToHDMI_0_0/OscopeWithZynq_acquireToHDMI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OscopeWithZynq_acquireToHDMI_0_0 || ORIG_REF_NAME==OscopeWithZynq_acquireToHDMI_0_0} -quiet] -quiet

# IP: bd/OscopeWithZynq/ip/OscopeWithZynq_auto_pc_0/OscopeWithZynq_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OscopeWithZynq_auto_pc_0 || ORIG_REF_NAME==OscopeWithZynq_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/small/OscopeWithZynq/OscopeWithZynq.gen/sources_1/bd/OscopeWithZynq/OscopeWithZynq_ooc.xdc
